### ISSUE TITLE
512 megabyte bug

### ISSUE THREAD

**Issue by R0fael** [Ncleardev/NclearOS-2#3]
Message when I use exactly 512mb of ram
![error](https://github.com/Ncleardev/NclearOS-2/assets/77662857/fe2f789a-6839-488f-81e7-908e65ed3f53)

**Comment by Ncleardev** [comment]
[v0.5.0](https://github.com/Ncleardev/NclearOS-2/releases/tag/v0.5.0) fixes that issue, thanks for reporting.
