### ISSUE TITLE
Virus detected - v0.5.0 - Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by amysthat** [Ncleardev/NclearOS-2#4]
v0.5.0 was released five days ago (according to the time of writing) and Windows Defender flags it as a virus. Previous version (0.4.0) doesn't trigger this.

It gets flagged as "Trojan:Script/Wacatac.B!ml", with a little search I found that this appereantly this is a Machine Learning thing and may lead to false positives, however don't take my word for it. I'm no cybersecurity expert.

Upon uploading it to virus total, no detections. Interestingly "Microsoft" is "timed out".

**Comment by Ncleardev** [comment]
Thanks for reporting, had no idea about this. I rebuilt the .iso file with a single character changed and that seemed to solve the problem.

**Comment by Ncleardev** [comment]
Nevermind, the real problem seemed to be the size - if my .iso file exceeds 10MB, it is detected as a virus. I changed the wallpaper resolution down to 648p (from 720p).
