### ISSUE TITLE
Changing wallpaper causes a memory leak

### ISSUE THREAD

**Issue by amysthat** [Ncleardev/NclearOS-2#5]
Upon pressing "Change Wallpaper" on the settings app, it's possible to see that the used RAM goes up in the Process Manager or System Info. If you change wallpaper enough, the system locks. My best guess is the old wallpaper is not deloaded. Probably using `Heap.Collect` is enough.

**Comment by Ncleardev** [comment]
Changing the wallpaper involves several processes:

- Desktop Wallpaper: The wallpaper image is resized from original bitmap to match the screen resolution.
- Blur Effects: First, the bitmap is resized to a lower resolution, such as 360p, to reduce resource consumption in subsequent steps. The resized bitmap is blurred, and then the blurred image is darkened. Finally, the image is resized back to match the screen resolution.
When necessary, the blurred bitmap is cropped for elements such as menus and window borders to achieve the desired blurred effect.

Unfortunately, these bitmap functions cause memory leaks. A call to `Heap.Collect` is already made during every `GUI.Refresh`. However, attempting to include `Heap.Collect` inside a loop for these functions results in system freezing.

In the next version I will consider adding an option to disable blur effects and also implementing a safety feature to prevent system freezing in case the blur effect operation exceeds available RAM.

**Comment by amysthat** [comment]
Oh, I did not know that. Is this issue a "considered resolved" then? It appears you had already acknowledged this.
